Tshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from store.views import home,cart,login,orders,signup,signout,logout,show_product,add_to_cart,checkout
from store.views import validatePayment
from .import views


urlpatterns = [
    path('' ,home ,name='homepage'),
    path('cart' ,cart),
    path('login' ,login, name='login'),
    path('orders' ,orders, name='orders'),
    path('signup' ,signup),
    path('checkout' ,checkout),
    path('logout' ,signout),
    path('product/<str:slug>' ,show_product),
    path('addtocart/<str:slug>/<str:size>' ,add_to_cart),
    path('validate_payment' ,validatePayment),
    
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class TshirtProperty(models.Model):
    title = models.CharField(max_length=30, null=False)
    slug =models.CharField(max_length=30, null=False ,unique=True)

    def __str__(self):
        return self.title
    
    
    
    class Meta:
        abstract =True


# Create your models here.
class occasion(TshirtProperty):
   pass
    
class IdealFor(TshirtProperty):
   pass
    
class NeckType(TshirtProperty):
   pass
    

class Sleeve(TshirtProperty):
   pass
    

class Brand(TshirtProperty):
   pass
    

class Color(TshirtProperty):
   pass
    


class Tshirt(models.Model):
    name = models.CharField(max_length=50 ,null=False)
    slug = models.CharField(max_length=200 ,null=True, unique=True ,default="")
    description = models.CharField(max_length=500 ,null=True)
    discount = models.IntegerField(default=0)
    image =models.ImageField(upload_to='upload/images' ,null=False)
    occasion = models.ForeignKey(occasion ,on_delete = models.CASCADE)
    brand = models.ForeignKey(Brand ,on_delete = models.CASCADE)
    sleeve = models.ForeignKey(Sleeve ,on_delete = models.CASCADE)
    neck_type = models.ForeignKey(NeckType ,on_delete = models.CASCADE)
    ideal_for = models.ForeignKey(IdealFor ,on_delete = models.CASCADE)
    color = models.ForeignKey(Color ,on_delete = models.CASCADE)
    def __str__(self):
        return self.name

class sizevariant(models.Model):

   SIZES = (
        ('S',"Small."),
        ('M',"Medium"),
        ('L',"Large"),
        ('XL',"Extra Large"),
        ('XXL',"Extra Extra Large"),
    )
   price = models.IntegerField(null= False)
   tshirt = models.ForeignKey(Tshirt ,on_delete =models.CASCADE)
   size = models.CharField(choices=SIZES ,max_length=5)

   def __str__(self):
      return f'{self.size}'
   

class Cart(models.Model):
   sizevariant = models.ForeignKey(sizevariant ,on_delete = models.CASCADE)
   quantity = models.IntegerField(default=1)
   user = models.ForeignKey(User ,on_delete = models.CASCADE)


class Orders(models.Model):
   orderstatus = (
        ('PENDING',"Pending"),
        ('PLACED',"Placed"),
        ('CANCELED',"Canceled"),
        ('COMPLETED',"Completed "),
    )
   method = (

        ('ONLINE',"Online"),
    )

   order_status = models.CharField(max_length=15 , choices=orderstatus)
   payment_method = models.CharField(max_length=15 , choices=method)
   shipping_address = models.CharField(max_length=100 , null=False)
   phone = models.CharField(max_length=10 , null=False)
   user = models.ForeignKey(User ,on_delete = models.CASCADE)
   total = models.IntegerField(null=False)
   date = models.DateTimeField(null=False ,auto_now_add=True)
   def __str__(self):
      return f'{self.shipping_address} - {self.phone}'

class Order_items(models.Model):
   order = models.ForeignKey(Orders ,on_delete = models.CASCADE)
   tshirt = models.ForeignKey(Tshirt ,on_delete = models.CASCADE)
   size = models.ForeignKey(sizevariant ,on_delete = models.CASCADE)
   quantity = models.IntegerField(null=False)
   price = models.IntegerField(null=False)
   date = models.DateTimeField(null=False ,auto_now_add=True)
   def __str__(self):
      return self.tshirt.name

class Payments(models.Model):
   order = models.ForeignKey(Orders ,on_delete = models.CASCADE)
   date = models.DateTimeField(null=False ,auto_now_add=True)
   payment_status = models.CharField(max_length=15, default="FAILED")
   payment_id = models.CharField(max_length=60)
   payment_request_id = models.CharField(max_length=60, unique=True, null=False)
   
   def __str__(self):
      return f'{self.payment_id}'
   

store/forms/authforms.py
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class CustomerAuthForm(AuthenticationForm):
    username = forms.EmailField(required=True ,label="Email")


class CustomerCreationForm(UserCreationForm):

    username = forms.EmailField(required=True ,label="Email")
    first_name = forms.CharField(required=True ,label="First Name")
    last_name = forms.CharField(required=True ,label="Last Name")

    def clean_first_name(self):
        value = self.cleaned_data.get('first_name')
        if len(value.strip()) < 4 :
            raise ValidationError("First Name must be 4 char long...")
        return value.strip()

    def clean_last_name(self):


        value = self.cleaned_data.get('last_name')
        if len(value.strip()) < 4 :
            raise ValidationError("Last Name must be 4 char long...")
        return value.strip()

    class meta:
        model = User
        fields =['username', 'first_name', 'last_name']

store/forms/checkout_form.py
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from store.models import Orders

class CheckForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = [
            'shipping_address','phone','payment_method'
        ]

store/views.py
from django.shortcuts import render,HttpResponse,redirect
from store.forms.authforms import CustomerCreationForm,CustomerAuthForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate ,login as loginUser,logout
from store.models import Tshirt,sizevariant,Cart,Orders,Order_items,Payments,occasion,Brand,Color,IdealFor,NeckType,Sleeve
from store.forms.checkout_form import CheckForm
from django.contrib.auth.decorators import login_required
from instamojo_wrapper import Instamojo
from Tshop.settings import API_KEY ,AUTH_TOKEN
API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/')




from django.db.models import Min

# Create your views here.

#Home
def home(request):
    query = request.GET
    
    tshirts=[]
    tshirts = Tshirt.objects.all()
    brand =query.get('brand')
    color = query.get('color')
    sleeve = query.get('sleeve')
    if brand != '' and brand is not None:
        tshirts = tshirts.filter(brand__slug=brand)
    if color != '' and color is not None:
        tshirts = tshirts.filter(color__slug=color)
    if sleeve != '' and sleeve is not None:
        tshirts = tshirts.filter(sleeve__slug=sleeve)

    brands =Brand.objects.all()
    sleeves =Sleeve.objects.all()   
    colors =Color.objects.all() 

    print(tshirts)

    context= {
        "tshirts":tshirts,
        "brands": brands,
        'colors': colors,
        'sleeves': sleeves,
       }
    return render(request ,template_name='store/home.html', context=context)

#cart
def cart(request):
    cart= request.session.get('cart')
    if cart is  None:
        cart=[]
    
    for c in cart:
        tshirt_id=c.get('tshirt')
        tshirt = Tshirt.objects.get(id=tshirt_id)
        c['size'] = sizevariant.objects.get(tshirt=tshirt_id, size = c['size'])
        c['tshirt']=tshirt
    return render(request ,template_name='store/cart.html',context={'cart':cart})

#login
def login(request):
    if (request.method) == 'GET':
        form = CustomerAuthForm()
        next_page = request.GET.get('next')
        if next_page is not None:
            request.session['next_page'] = next_page

        return render(request ,template_name='store/login.html', context={ 'form':form})


    else:
        form=CustomerAuthForm(data =request.POST)
        if form.is_valid():
            username =form.cleaned_data.get('username')
            password =form.cleaned_data.get('password')
            user = authenticate(username = username ,password=password)
            if user:
                loginUser(request,user)

                session_cart =request.session.get('cart')
                if session_cart is None:
                    session_cart=[]
                else:
                    for c in session_cart:
                        size = c.get('size')
                        tshirt_id = c.get('tshirt')
                        quantity = c.get('quantity')
                        cart_obj = Cart()
                        cart_obj.sizevariant = sizevariant.objects.get(size =size , tshirt = tshirt_id)
                        cart_obj.quantity = quantity
                        cart_obj.user = user
                        cart_obj.save()


                cart = Cart.objects.filter(user = user)
                session_cart = []
                for c in cart:
                    obj={
                        'size' : c.sizevariant.size,
                        'tshirt': c.sizevariant.tshirt.id,
                        'quantity': c.quantity
                    }
                    session_cart.append(obj)

                request.session['cart'] = session_cart
                next_page = request.session.get("next_page")
                if next_page is None:
                    next_page = 'homepage'
                return redirect(next_page)

        else:
            return render(request ,template_name='store/login.html', context={ 'form':form})



#order
@login_required(login_url = '/login')
def orders(request):
    user = request.user
    orders =Orders.objects.filter(user = user ).order_by('-date').exclude(order_status='PENDING')
    context = {
            "orders" : orders

    }
    return render(request ,template_name='store/orders.html', context=context)


#signup
def signup(request):

    if (request.method =='GET'):

        form = CustomerCreationForm()
        context ={
            "form":form}
        return render(request ,template_name='store/signup.html' ,context=context)
    else:
        form = CustomerCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()
            user.first_name =user.username
            user.save() 

            return redirect('login')
        context ={
            "form":form}
        return render(request ,template_name='store/signup.html' ,context=context)

#logout
def signout(request):
    logout(request)
    return redirect('homepage')

def show_product(request , slug):
    tshirt = Tshirt.objects.get(slug=slug)
    size = request.GET.get('size')

    if size is None:
        size = tshirt.sizevariant_set.all().order_by('price').first()
    else:
        size = tshirt.sizevariant_set.get(size=size)
 
    size_price = size.price
    sell_price = size_price -(size_price*(tshirt.discount//100))

    context = {'tshirt' : tshirt , 'price':size_price , 'sell_price':sell_price ,'active_size':size}
    return render(request , template_name='store/product_details.html',context=context)

#product import in cart

def add_to_cart(request, slug , size):
    user=None
    if request.user.is_authenticated:
        user=request.user

    cart = request.session.get('cart')
    if cart is None:
        cart=[]

    tshirt = Tshirt.objects.get(slug=slug)
    add_cart_to_anom_user(cart, size ,tshirt)
    
    
        
    if user is not None:
        add_cart_to_database(user ,size ,tshirt)
       


    
        
    request.session['cart'] =cart
    return_url=request.GET.get('return_url')
    return redirect(return_url)

def add_cart_to_database(user ,size, tshirt):
    size =sizevariant.objects.get(size=size ,tshirt = tshirt)
    existing = Cart.objects.filter(user = user ,sizevariant =size)
    if len(existing) > 0:
        obj = existing[0]
        obj.quantity = obj.quantity+1
        obj.save()
    
    else:
        c =Cart()
        c.user=user
        c.sizevariant = size
        c.quantity = 1
        c.save()

def add_cart_to_anom_user(cart ,size ,tshirt):
    flag=True
    for cart_obj in cart:
        t_id=cart_obj.get('tshirt')
        size_short=cart_obj.get('size')
        if t_id == tshirt.id and size==size_short:
            flag=False
            cart_obj['quantity']+=1

    if flag:
        cart_obj={
            'tshirt': tshirt.id,
            'size':size,
            'quantity': 1

        }
        cart.append(cart_obj)
#utility function
def cal_total_payable_amount(cart):
    total = 0
    for c in cart:
        discount =c.get('tshirt').discount
        price = c.get('size').price
        sale_price =(price - ( price * ( discount // 100) ))
        total_of_single_product = sale_price * c.get('quantity')
        total = total + total_of_single_product
        
    return total

@login_required(login_url = '/login')
def checkout(request):
    #get request
    if request.method == 'GET':
        form =CheckForm()
        return render(request , template_name='store/checkout.html' ,context={'form' : form})
    else:
        #post request
        form = CheckForm(request.POST)
        user= None
        if request.user.is_authenticated:
            user = request.user
        if form.is_valid():
            #payment
            cart =request.session.get('cart')
            if cart is None:
                cart=[]
            for c in cart:
                size_str = c.get('size')
                tshirt_id = c.get('tshirt')
                size_obj = sizevariant.objects.get(size=size_str, tshirt=tshirt_id)
                c['size'] = size_obj
                c['tshirt'] = size_obj.tshirt

            shipping_address = form.cleaned_data.get('shipping_address')
            phone = form.cleaned_data.get('phone')
            payment_method = form.cleaned_data.get('payment_method')
            total = cal_total_payable_amount(cart)
            print(shipping_address, phone, payment_method, total)

            order = Orders()
            order.shipping_address = shipping_address
            order.phone = phone
            order.payment_method = payment_method
            order.total = total
            order.order_status = "PENDING"
            order.user = user
            order.save()

            for c in cart:
                OrderItem = Order_items()
                OrderItem.order = order
                size = c.get('size')
                tshirt = c.get('tshirt')
                OrderItem.price =(size.price -(size.price *(tshirt.discount / 100)))
                OrderItem.quantity = c.get('quantity')
                OrderItem.size = size
                OrderItem.tshirt = tshirt
                OrderItem.save()
            #payment
            response = API.payment_request_create(
                amount=order.total,
                purpose="Payment For Tshirts",
                send_email=False,
                buyer_name=f'{user.first_name} {user.last_name}',
                email=user.email,
                redirect_url="http://localhost:8000/validate_payment")

            payment_request_id = response['payment_request']['id']
            url = response['payment_request']['longurl']

            payment = Payments()
            payment.order = order
            payment.payment_request_id = payment_request_id
            payment.save()
            return redirect(url)
            
        else:
            return redirect('/checkout')

def validatePayment(request):
    user = None

store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Tshirt-Bazar</title>
    <style>
        .display-5{
            font-size: 30px;
            font-weight: 300;
        }
    </style>
</head>

<body>
    <!--navbar start-->
    <nav class="navbar sticky-top navbar-expand-lg navbar-light"style="background-color:#e3f2fd";>
        <a class="navbar-brand" href="/#"><h3><b style="color:#912702 ; font-family:Algerian; font-size:31px;">Tshirt-Bazar</b></h3></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-danger" ><b>This Website is developed by Vishwadeep Singh and Team for Project purpose</b> <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/cart">Cart <span class="badge badge-info">{{request.session.cart|length}}</span></a>
                </li>
                {% if request.user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>

                
                <li class="nav-item">
                    <a class="nav-link" href="/orders">Orders</a>
                </li>
                
                {% else%}
                
                
                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="/signup">Signup</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- navbar end-->

    {% block content %} 

    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

store/templates/store/cart.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %} 

<div class="container">
    <div>
        <table class="table table-hover table-stripped">
            <thead>
                <tr>
                    <th>S.No.</th>
                    <th>Image</th>
                    <th>Tshirt</th>
                    <th>Size</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Sale Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for c in cart%}

                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img height="70px" class="img rounded-circle" src="{{c.tshirt.image.url}}" alt=""></td>
                    <td>{{c.tshirt.name}}</td>
                    <td>{{c.size.size}}</td>
                    <td>{{c.size.price|rupee}}</td>
                    <td>{{c.tshirt.discount}}%</td>
                    <td>{%clc_sale_price c.size.price c.tshirt.discount as sale_price %}{{sale_price|rupee}}</td>
                    <td class="">{{c.quantity}}</td>
                    <td>{% multiply c.quantity sale_price as total%}<b>{{total|rupee}}</b></td>
                </tr>

                {% endfor%}
                <tfoot>
                    <tr>
                        <th colspan="3"></th>
                        <th colspan="5" style="font-size: 23px;">Payable Amount</th>
                        <th style="font-size: 23px;">{{cart|cal_total_payable_amount|rupee}}</th>
                    </tr>
                    <tr>
                        <th colspan="7"></th>
                        <th colspan="2"><a href="/checkout" class="btn btn-outline-success ">Place Order</a></th>
                        
                    </tr>
                </tfoot>

            </tbody>
        </table>

    </div>

</div>

{% endblock %}

store/templates/store/checkout.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block content %} 
<div class="container">
    <div class="p-2">
        <div class="display-5">
            Checkout page
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-7 mx-auto border rounded p-3"style="background-color:#e3f2fd ;">
                <form action="/checkout" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <hr>
                    <div class="form-group">
                        <input type="submit" value="Checkout" class="btn btn-outline-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

store/templates/store/home.html
{% extends "./base.html " %}
{% include './popup.html' %}
{% load tshirt_tags %}
{% load filter_tags %}

{% block content %}
{% include './popup.html' %}
<div class="container-fluid">
    <div class="row m-1">
      <div class="col-2 border rounded" style="background-color:#e3f2fd";>
        <!--filter-->
        <form id="filterForm" action="/">
          <h4 class="mt-3">Filters</h4>
          <hr>
          <div>
            <!--brands-->
            <div class="form-group">
              <label for="brand">Brand</label>
              <select onchange="sumitForm()" class="form-control" name="brand" id="brands" style="background-color:#e3f2fd";>
                <option value="">Select Brand</option>
                {% for brand in brands %}
  
                <option
                {% selected_attr request.GET.brand brand.slug%}
                value="{{brand.slug}}">{{brand.title}}</option>
                {%endfor%}
              </select>
            </div>
            <!--Colors-->
            <div class="form-group">
              <label for="color">Colors</label>
              <select onchange="sumitForm()"  class="form-control" name="color" id="color" style="background-color:#e3f2fd";>
                <option value="">Select Color</option>
                {% for color in colors %}
  
                <option
                {% selected_attr request.GET.color color.slug%}
                value="{{color.slug}}">{{color.title}}</option>
                {%endfor%}
              </select>
            </div>
            <!--sleeves-->
            <div class="form-group">
              <label for="sleeve">Sleeve</label>
              <select onchange="sumitForm()"  class="form-control" name="sleeve" id="sleeve" style="background-color:#e3f2fd";>
                <option value="">Select Sleeve</option>
                {% for sleeve in sleeves %}
  
                <option {% selected_attr request.GET.sleeve sleeve.slug%} value="{{sleeve.slug}}">{{sleeve.title}}</option>
                {%endfor%}
              </select>
            </div>
            <hr>
            <a href="/" class="btn btn-success btn-sm">Clear Filter</a>
          </div>
  
        </form>
      </div>
      <div class="col border rounded " >
        <div class="row">
          
        {% for tshirt in tshirts %}
        <div class="col-4 mx-auto mt-2">
            <div class="card h-100" style="width: 18rem;">
                <img class="card-img-top"height=350px src="{{tshirt.image.url}}" alt="Card image cap">
                <div class="card-body">
                  <h6 class="card-title">{{tshirt|title}}</h6>
                  <span> {% sale_price tshirt as sale_price_result%}</span>
                    <b>{{sale_price_result|rupee}}</b>
                  &nbsp;
                  <span > {% min_price tshirt as result%}</span>
                  <del class="text-danger">{{result|rupee}}</del>
                  
                  
                  <span class="float-right badge badge-info">Save {{tshirt.discount}}%</span>
                  
                    

                </div>

                <div class="card-footer p-0 ">
                    <a href="/product/{{tshirt.slug}}" class="btn btn-light btn-block"style="background-color:#e3f2fd">See More</a>

                </div>
              </div>
            
        </div>
        
        {% endfor %}
        </div>
        </div>
      </div>
</div>

<script>
  function sumitForm(){
    document.getElementById('filterForm').submit()

  }
</script>
{% endblock %}

store/templates/store/login.html
{% extends "./base.html" %}

{% block content %} 
{% load crispy_forms_tags %}
<div class="col-lg-4 mx-auto border rounded p-3 mt-4"style="background-color:#e3f2fd ;">
    <form action="/login" method="post">
     {% csrf_token %}
     
    <h1 class="display-6 mt-3 text-center" style="font-family: SemiCondensed;">Login Here</h1>
    <div class="text-center pt-4">
        <img height="150px" src="https://inktothepeople.com/images/uploaded/Ink%20Logos/ink-logo-red1.png" alt="">

    </div>
  
     <hr>
     {{ form|crispy }}
 <div class="form-group">
   <input type="Submit" value="Login" class="btn btn-info">
 </div>
 <hr>
 <div 
  style="font-family: SemiCondensed;" >
  Don't have an account? <a href="/signup">Sign Up</a>
 </div>
 
    </form>
 </div>

{% endblock %}

store/templates/store/orders.html
{% extends "./base.html" %}
{% load tshirt_tags %}

{% block content %} 

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>S.No.</th>
                <th>Date</th>
                <th>Items</th>
                <th>Status</th>

            </tr>
        </thead>
        <tbody>
            {% for  order in orders %}
            <tr>
                <td>{{ forloop.counter}}</td>
                <td>{{ order.date|date}}</td>
                <td>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Image</th>
                                <th>T-shirt</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>TOTAL</th>


                            </tr>
                        </thead>
                        <tbody>
                            
                                {% for oi in order.order_items_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><img src="{{oi.tshirt.image.url}}" height = 60px alt=""></td>
                                <td>{{oi.tshirt.name}}</td>
                                <td>{{oi.price|rupee}}</td>
                                <td>{{oi.quantity}}</td>
                                <td>{% multiply oi.quantity oi.price as result%}{{result|rupee}}</td>

                           
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                </td>
                <td>
                    {% if order.order_status == 'COMPLETED' %}
                    <span class="badge badge-success">{{order.order_status}}</span>

                    {% elif order.order_status == 'PLACED' %}
                    <span class="badge badge-warning">{{order.order_status}}</span>
                    
                    {% else %}
                    <span class="badge badge-danger">{{order.order_status}}</span>

                    {% endif%}

                </td>

            </tr>

            {% endfor%}
        </tbody>
    </table>
</div>

{% endblock %}

store/templates/store/payment_failed.html
{% extends "./base.html" %}

{% block content %} 

<div class="jumbotron container alert alert-danger mx-auto mt-4">
    <h1 class="display-3">Payment Failed !!</h1>
    <p class="lead">Your Payment is Failed , Please Try again ..!!</p>
    <hr class="my-2">
    
</div>

{% endblock %}

store/templates/store/signup.html
{% extends "./base.html" %}

{% block content %} 
{% load crispy_forms_tags %}
<div class="col-lg-4 mx-auto border rounded p-3 mt-4"style="background-color:#e3f2fd ;">
   <form action="/signup" method="post">
    {% csrf_token %}
    <h1 class="display-6 mt-3 " style="font-family: SemiCondensed;">Create Your Account</h1>
    <div style="font-family: SemiCondensed;">
      Already have account ? <a href="/login">Login</a>
    </div>
    <hr>
    {{ form|crispy }}
<div class="form-group">
  <input type="Submit" value="Create an account" class="btn btn-info">
</div>

   </form>
</div>

{% endblock %}